"""Lightweight bilingual localization for the parallel QML desktop."""

from __future__ import annotations

from typing import Final

from PySide6.QtCore import Property, QObject, Signal, Slot

from market_vault.desktop.preferences import (
    DesktopPreferenceStore,
    SUPPORTED_LANGUAGES,
)


EN: Final[dict[str, str]] = {
    "app.title": "MarketVault",
    "app.subtitle": "Local market data vault",
    "language.control": "Language",
    "nav.group.home": "HOME",
    "nav.group.data": "DATA",
    "nav.group.explore": "EXPLORE",
    "nav.group.research": "RESEARCH",
    "nav.group.quality": "QUALITY",
    "nav.group.activity": "ACTIVITY",
    "nav.group.advanced": "ADVANCED",
    "nav.home": "Home",
    "nav.historical_data": "Historical Data",
    "nav.trading_calendar": "Trading Calendar",
    "nav.market_data": "Market Data",
    "nav.inventory": "Inventory",
    "nav.quant_research": "Quant Research",
    "nav.coverage_audit": "Coverage Audit",
    "nav.intraday_audit": "Intraday Audit",
    "nav.runs": "Runs",
    "nav.storage_cleanup": "Storage & Cleanup",
    "home.title": "Home",
    "home.refresh": "Refresh Dashboard",
    "home.refreshing": "Refreshing...",
    "home.unconfigured": "Dashboard unconfigured",
    "home.recent_runs": "Recent Runs",
    "home.no_recent_runs": "No recent runs",
    "home.ping": "Ping Python",
    "status.bridge": "Bridge",
    "status.dashboard": "Dashboard",
    "metric.symbols": "Symbols",
    "metric.snapshots": "Snapshots",
    "metric.latest_rows": "Latest rows",
    "metric.completed_dates": "Completed dates",
    "metric.incomplete_dates": "Incomplete dates",
    "metric.latest_trade_date": "Latest trade date",
    "columns.run_kind": "Run type",
    "columns.dataset": "Dataset",
    "columns.run_id": "Run ID",
    "columns.started_at": "Started",
    "columns.finished_at": "Finished",
    "columns.status": "Status",
    "columns.row_count": "Rows",
    "columns.requested_items": "Requested items",
    "columns.errors": "Errors",
    "common.query": "Query",
    "common.refresh": "Refresh",
    "common.export_csv": "Export CSV",
    "common.export_json": "Export JSON",
    "common.previous": "Previous",
    "common.next": "Next",
    "common.no_data": "No data loaded",
    "common.page": "Page",
    "common.of": "of",
    "common.rows": "rows",
    "common.status": "Status",
    "common.summary": "Summary",
    "common.cancel": "Cancel",
    "common.confirm": "Confirm",
    "common.ready": "Ready",
    "common.running": "Running",
    "common.close_busy": "An operation is still running. Wait for it to finish before closing.",
    "common.error": "Error",
    "status.ready": "Ready",
    "status.running": "Running",
    "status.success": "Success",
    "status.failed": "Failed",
    "status.busy": "Busy",
    "status.unconfigured": "Unconfigured",
    "status.unreviewed": "Not reviewed",
    "status.planned": "Planned",
    "status.refused": "Refused",
    "status.empty": "Empty",
    "status.partial": "Partial",
    "status.validation_error": "Validation error",
    "operation.dashboard": "Dashboard refresh",
    "operation.market_data": "Market data query",
    "operation.calendar_query": "Calendar query",
    "operation.calendar_collect": "Calendar collection",
    "operation.backfill_plan": "Backfill plan",
    "operation.backfill_execute": "Backfill execution",
    "operation.inventory": "Inventory",
    "operation.quant_inspect": "Research Dataset verification",
    "operation.research_workspace_preview": "Research workspace preview",
    "operation.research_workspace_build": "Research Dataset build",
    "operation.research_backfill_execute": "Prepare research-ready market data",
    "operation.feature_research": "Feature research",
    "operation.backtest": "Backtest",
    "operation.coverage_audit": "Coverage audit",
    "operation.intraday_audit": "Intraday audit",
    "operation.runs": "Run history",
    "operation.storage_review": "Storage review",
    "operation.storage_execute": "Safe Purge execution",
    "operation.export": "Export",
    "opend.title": "Confirm OpenD operation",
    "opend.message": "This operation may connect to OpenD.",
    "opend.operation": "Operation",
    "opend.host": "Host",
    "opend.port": "Port",
    "field.symbols": "Symbols",
    "field.code": "Code",
    "field.start_date": "Start date",
    "field.end_date": "End date",
    "field.bootstrap_start_date": "Bootstrap start date",
    "field.calendar_market": "Calendar market",
    "field.calendar_code": "Calendar code",
    "field.scope": "Scope",
    "field.market": "Market",
    "field.interval": "Interval",
    "field.requested_session": "Requested session",
    "field.bar_session": "Bar session",
    "field.session": "Session",
    "field.adjustment": "Adjustment",
    "field.page_size": "Page size",
    "field.max_retries": "Max retries",
    "field.retry_backoff": "Retry backoff (seconds)",
    "field.force": "Force recollection",
    "field.incremental": "Incremental",
    "field.status": "Status",
    "field.dataset": "Dataset",
    "field.source": "Source",
    "field.source_schema_version": "Source schema version",
    "field.confirmation": "Exact confirmation",
    "field.cleanup_policy": "Cleanup policy",
    "historical.plan": "Plan locally",
    "historical.execute": "Execute via OpenD",
    "historical.plan_items": "Backfill plan items",
    "calendar.local_query": "Query local",
    "calendar.fetch": "Fetch from OpenD",
    "market.query": "Query local data",
    "inventory.inspect": "Inspect inventory",
    "audit.run": "Run local audit",
    "runs.refresh": "Refresh runs",
    "storage.warning": "Files are moved to retained quarantine. Permanent deletion is not supported.",
    "storage.review": "Review scope",
    "storage.execute": "Execute Safe Purge",
    "storage.plan_id": "Reviewed plan ID",
    "storage.refusals": "Refusal reasons",
    "storage.confirmation_help": "Enter exactly PURGE <plan_id> after reviewing an executable plan.",
    "storage.policy.exact_scope": "Exact Scope",
    "storage.policy.superseded_only": "Superseded Only",
    "quant.dataset_path": "Research Dataset directory",
    "quant.dataset_placeholder": "D:\\...\\multi-source-cross-day-dataset-<id>",
    "quant.dataset_help": "Use one exact verified Research Dataset artifact. No latest discovery and no network access.",
    "quant.inspect": "Verify Dataset",
    "quant.browse": "Browse...",
    "quant.choose_dataset": "Choose Research Dataset directory",
    "quant.builder_tab": "Dataset Builder",
    "quant.builder_symbol": "Research symbol",
    "quant.builder_preset": "Feature preset",
    "quant.builder_horizon": "Future horizon (trading days)",
    "quant.builder_cohort": "Research cohort",
    "quant.builder_preview": "Check Build Readiness",
    "quant.builder_prepare": "Prepare via OpenD",
    "quant.builder_build": "Build Dataset",
    "quant.builder_help": "Preview first. Prepare via OpenD explicitly collects the research-ready 10.9-mv-ts2 / RTH / NONE cohort when needed. Build Dataset is local-only and materializes verified Canonical and Research Dataset artifacts, then loads the new Dataset automatically.",
    "quant.feature_tab": "Factor Research",
    "quant.backtest_tab": "Backtest",
    "quant.comparison_tab": "Strategy Comparison",
    "quant.common_features": "Common Features (comma separated)",
    "quant.add_strategy": "Add",
    "quant.remove_strategy": "Remove",
    "quant.strategy_name": "Strategy name",
    "quant.strategy_kind": "Strategy type",
    "quant.feature_rule": "Feature rule",
    "quant.composite_rule": "Composite rule",
    "quant.condition_match": "Match",
    "quant.match_all": "ALL conditions",
    "quant.match_any": "ANY condition",
    "quant.add_condition": "Add condition",
    "quant.condition_columns": "Feature / comparison / threshold (Dataset units)",
    "quant.trend_feature": "Trend Feature (GT)",
    "quant.trend_threshold": "Trend threshold (>)",
    "quant.reversion_feature": "Mean reversion Feature (LT)",
    "quant.reversion_threshold": "Mean reversion threshold (<)",
    "quant.ridge_alpha": "Ridge alpha",
    "quant.ridge_threshold": "Predicted return threshold (>)",
    "quant.train_periods": "Minimum training periods",
    "quant.validation_periods": "Validation periods per fold",
    "quant.step_periods": "Step periods",
    "quant.run_comparison": "Compare Strategies",
    "quant.include_equity": "Include bar-close valuation",
    "quant.include_risk": "Include benchmark & risk",
    "quant.risk_results": "Benchmark & risk",
    "quant.risk_help": "Daily returns use complete recorded session closes. Annualization: 252; risk-free rate: 0. n < 2 means too few daily returns; σ = 0 means zero volatility. Sharpe is undefined in either case. Total return includes the full window. Benchmark uses the same costs and price convention, without dividend reinvestment.",
    "quant.benchmark_legend": "Gold: selected curve. Grey: buy-and-hold price benchmark at the same costs.",
    "summary.risk_report_id": "Risk report ID",
    "columns.return_difference": "Return minus benchmark",
    "columns.annualized_volatility": "Annualized volatility",
    "columns.sharpe_ratio": "Sharpe (RF=0)",
    "columns.daily_return_count": "Daily returns (n)",
    "columns.risk_status": "Risk availability",
    "quant.collapse_inputs": "Hide parameters",
    "quant.expand_inputs": "Show parameters",
    "quant.comparison_results": "Comparison results",
    "quant.equity_ledger": "Equity & ledger",
    "quant.bar_equity": "Bar-close equity",
    "quant.equity_help": "Initial equity 1.0; cash and fractional shares. Marks update at recorded bar availability and fills. No intrabar price path.",
    "summary.equity_comparison_id": "Equity comparison ID",
    "columns.bar_close_max_drawdown": "Bar-close max DD",
    "columns.timestamp": "Time (UTC)",
    "columns.event": "Event",
    "columns.cash": "Cash",
    "columns.quantity": "Shares",
    "columns.mark_price": "Mark price",
    "columns.market_value": "Position value",
    "columns.equity": "Equity",
    "columns.drawdown": "Drawdown",
    "columns.transaction_cost": "Event cost",
    "quant.comparison_help": "Development validation only; TEST stays held out. Every rule Feature must be in the comma-separated common projection, also used by Ridge. Periods count distinct sample timestamps. Expand parameters to edit the next comparison.",
    "quant.open_experiment": "Open experiment",
    "quant.save_experiment": "Save experiment",
    "quant.replay_experiment": "Verify replay",
    "quant.replay_relocated": "Choose Dataset & replay",
    "quant.snapshot_loaded": "Saved run; replay not verified",
    "quant.replay_verified": "Complete replay matched",
    "quant.experiment_help": "Save the last successful run. Open works offline; replay checks the full result.",
    "quant.diagnose_strategy": "Diagnose",
    "quant.diagnostics_title": "Parameter and cost diagnostics",
    "quant.diagnostics_help": "Choose one strategy from the current form. Enter explicit values for up to two axes and explicit per-side costs. At most 64 evaluations; all use the same development validation windows and held-out TEST.",
    "quant.no_axis": "No parameter axis",
    "quant.condition_axis": "Condition threshold",
    "quant.first_axis": "First parameter axis",
    "quant.second_axis": "Second parameter axis",
    "quant.axis_values": "Values, separated by commas",
    "quant.cost_scenarios": "Commission/slippage (bps), e.g. 0/0,10/5",
    "quant.diagnostics_count": "Evaluations",
    "quant.run_diagnostics": "Run diagnostics",
    "quant.diagnostics_results": "All candidates",
    "quant.fold_contributions": "Fold contributions",
    "quant.diagnostic_candidate": "Candidate · commission/slippage",
    "quant.diagnostic_results_help": "Input order; return change compares each variant with the first cost scenario. Selecting a candidate changes the displayed cost group, equity and folds. Save/replay includes every candidate.",
    "quant.fold_help": "Net cash contribution on a continuous account starting at 1. Trades belong to their signal's validation fold, even when they exit later. Zero-trade folds remain visible; contributions sum to final net return within accounting tolerance.",
    "summary.evaluation_count": "Evaluations",
    "summary.variant_count": "Parameter variants",
    "summary.cost_scenario_count": "Cost scenarios",
    "columns.diagnostic_candidate": "Candidate",
    "columns.parameters": "Parameter values",
    "columns.commission_bps": "Commission (bps)",
    "columns.slippage_bps": "Slippage (bps)",
    "columns.return_change_from_first_cost": "Return Δ vs first cost",
    "columns.fold_index": "Validation fold",
    "columns.validation_start_time": "Validation start (UTC)",
    "columns.validation_end_time": "Validation end (UTC)",
    "columns.validation_sample_count": "Validation samples",
    "columns.cash_contribution": "Net cash contribution",
    "operation.strategy_diagnostics": "Strategy diagnostics",
    "summary.comparison_id": "Comparison ID",
    "summary.fold_count": "Folds",
    "summary.common_validation_rows": "Common validation samples",
    "summary.held_out_test_rows": "Held-out TEST samples",
    "columns.strategy": "Strategy",
    "columns.trade_count": "Trades",
    "columns.total_return": "Net return",
    "columns.gross_total_return": "Gross return",
    "columns.realized_max_drawdown": "Realized max DD",
    "columns.win_rate": "Win rate",
    "columns.profit_factor": "Profit factor",
    "columns.overlap_skipped_count": "Overlap skips",
    "columns.exposure": "Exposure",
    "operation.strategy_comparison": "Strategy comparison",
    "quant.label": "Label",
    "quant.split": "Split",
    "quant.quantiles": "Quantiles",
    "quant.run_feature": "Analyze Factors",
    "quant.feature_results": "Factor metrics",
    "quant.signal_feature": "Signal Feature",
    "quant.comparator": "Comparator",
    "quant.threshold": "Threshold",
    "quant.return_label": "Execution return Label",
    "quant.commission_bps": "Commission (bps/side)",
    "quant.slippage_bps": "Slippage (bps/side)",
    "quant.run_backtest": "Run Backtest",
    "quant.equity_curve": "Normalized equity",
    "quant.no_backtest": "Run a backtest to draw the equity curve",
    "quant.trades": "Trades",
    "summary.dataset_id": "Dataset ID",
    "summary.symbols": "Symbols",
    "summary.rows": "Rows",
    "summary.features": "Features",
    "summary.labels": "Labels",
    "summary.train_rows": "TRAIN",
    "summary.validation_rows": "VALIDATION",
    "summary.test_rows": "TEST",
    "summary.artifact_status": "Artifact",
    "summary.split": "Split",
    "summary.label": "Label",
    "summary.feature_count": "Features",
    "summary.sample_count": "Samples",
    "summary.best_feature": "Best |RankIC|",
    "summary.best_rank_ic": "RankIC",
    "summary.quantiles": "Quantiles",
    "summary.backtest_id": "Backtest ID",
    "summary.trade_count": "Trades",
    "summary.signal_count": "Signals",
    "summary.total_return": "Return",
    "summary.max_drawdown": "Max DD",
    "summary.win_rate": "Win rate",
    "summary.avg_trade_return": "Avg trade",
    "summary.profit_factor": "Profit factor",
    "summary.exposure": "Exposure",
    "summary.research_schema": "Research schema",
    "summary.symbol": "Symbol",
    "summary.interval": "Interval",
    "summary.preset": "Preset",
    "summary.horizon": "Horizon",
    "summary.trading_dates": "Trading dates",
    "summary.anchor_dates": "Anchor dates",
    "summary.missing_research_dates": "Missing research dates",
    "summary.feature_window_bars": "Feature window",
    "summary.train_end": "TRAIN end",
    "summary.validation_end": "VALIDATION end",
    "summary.test_end": "TEST end",
    "summary.build_ready": "Build ready",
    "summary.canonical_build_id": "Canonical build ID",
    "summary.canonical_rows": "Canonical rows",
    "summary.dataset_status": "Dataset status",
    "summary.dataset_rows": "Dataset rows",
    "summary.dataset_path": "Dataset path",
    "summary.research_data_prepare": "Research data prepare",
    "summary.successful_items": "Successful items",
    "summary.failed_items": "Failed items",
    "columns.calendar_profile": "Calendar profile",
    "columns.research_data": "Research data",
    "columns.role": "Research role",
    "columns.feature_name": "Feature",
    "columns.sample_count": "Samples",
    "columns.pearson_ic": "Pearson IC",
    "columns.rank_ic": "Rank IC",
    "columns.top_bottom_spread": "Top-Bottom spread",
    "columns.feature_mean": "Feature mean",
    "columns.feature_std": "Feature std",
    "columns.signal_time": "Signal time",
    "columns.entry_time": "Entry time",
    "columns.exit_time": "Exit time",
    "columns.signal_value": "Signal",
    "columns.gross_return": "Gross return",
    "columns.net_return": "Net return",
    "columns.equity_after": "Equity after",
    "columns.code": "Code",
    "columns.symbol": "Symbol",
    "columns.trade_date": "Trade date",
    "columns.requested_trade_date": "Requested trade date",
    "columns.interval": "Interval",
    "columns.session": "Session",
    "columns.adjustment": "Adjustment",
    "columns.state": "State",
    "columns.page": "Page",
    "columns.market": "Market",
    "columns.date": "Date",
    "columns.trade_date_type": "Trade date type",
    "columns.ingestion_run_id": "Ingestion run ID",
    "columns.source_state": "Source state",
    "columns.audit_status": "Audit status",
    "columns.boundary_evaluated": "Boundary evaluated",
    "columns.internal_gap_count": "Internal gaps",
    "columns.physical_scope_status": "Physical scope",
    "columns.symbols": "Symbols",
    "columns.dates": "Dates",
    "columns.affected_rows": "Affected rows",
    "columns.raw_bytes": "Raw bytes",
    "columns.curated_bytes": "Curated bytes",
    "columns.raw_path": "Raw path",
    "columns.curated_path": "Curated path",
    "columns.requested_session": "Requested session",
    "columns.source_schema_version": "Source schema version",
    "columns.superseded_run_id": "Superseded run ID",
    "columns.retained_run_id": "Retained run ID",
    "columns.superseded_ingested_at": "Superseded ingested at",
    "columns.retained_ingested_at": "Retained ingested at",
}

ZH_CN: Final[dict[str, str]] = {
    "app.title": "MarketVault",
    "app.subtitle": "本地市场数据仓库",
    "language.control": "语言",
    "nav.group.home": "首页",
    "nav.group.data": "数据",
    "nav.group.explore": "浏览",
    "nav.group.research": "量化研究",
    "nav.group.quality": "质量检查",
    "nav.group.activity": "运行",
    "nav.group.advanced": "高级管理",
    "nav.home": "首页",
    "nav.historical_data": "历史数据",
    "nav.trading_calendar": "交易日历",
    "nav.market_data": "行情数据",
    "nav.inventory": "数据库存",
    "nav.quant_research": "量化研究",
    "nav.coverage_audit": "覆盖检查",
    "nav.intraday_audit": "分钟数据检查",
    "nav.runs": "运行记录",
    "nav.storage_cleanup": "存储与清理",
    "home.title": "首页",
    "home.refresh": "刷新仪表盘",
    "home.refreshing": "正在刷新...",
    "home.unconfigured": "仪表盘未配置",
    "home.recent_runs": "最近运行",
    "home.no_recent_runs": "暂无运行记录",
    "home.ping": "测试 Python",
    "status.bridge": "桥接状态",
    "status.dashboard": "仪表盘",
    "metric.symbols": "标的数量",
    "metric.snapshots": "快照数量",
    "metric.latest_rows": "最新行数",
    "metric.completed_dates": "完整日期",
    "metric.incomplete_dates": "不完整日期",
    "metric.latest_trade_date": "最新交易日",
    "columns.run_kind": "运行类型",
    "columns.dataset": "数据集",
    "columns.run_id": "运行 ID",
    "columns.started_at": "开始时间",
    "columns.finished_at": "结束时间",
    "columns.status": "状态",
    "columns.row_count": "行数",
    "columns.requested_items": "请求项目",
    "columns.errors": "错误",
    "common.query": "查询",
    "common.refresh": "刷新",
    "common.export_csv": "导出 CSV",
    "common.export_json": "导出 JSON",
    "common.previous": "上一页",
    "common.next": "下一页",
    "common.no_data": "尚未加载数据",
    "common.page": "第",
    "common.of": "页，共",
    "common.rows": "行",
    "common.status": "状态",
    "common.summary": "摘要",
    "common.cancel": "取消",
    "common.confirm": "确认",
    "common.ready": "就绪",
    "common.running": "正在运行",
    "common.close_busy": "操作仍在运行，请等待完成后再关闭。",
    "common.error": "错误",
    "status.ready": "就绪",
    "status.running": "正在运行",
    "status.success": "成功",
    "status.failed": "失败",
    "status.busy": "忙碌",
    "status.unconfigured": "未配置",
    "status.unreviewed": "尚未检查",
    "status.planned": "已生成计划",
    "status.refused": "已拒绝",
    "status.empty": "无数据",
    "status.partial": "部分成功",
    "status.validation_error": "输入验证失败",
    "operation.dashboard": "刷新仪表盘",
    "operation.market_data": "查询行情数据",
    "operation.calendar_query": "查询交易日历",
    "operation.calendar_collect": "获取交易日历",
    "operation.backfill_plan": "生成回填计划",
    "operation.backfill_execute": "执行历史数据回填",
    "operation.inventory": "检查库存",
    "operation.quant_inspect": "验证研究数据集",
    "operation.research_workspace_preview": "检查研究数据集构建条件",
    "operation.research_workspace_build": "构建 Research Dataset",
    "operation.research_backfill_execute": "准备研究专用行情数据",
    "operation.feature_research": "因子研究",
    "operation.backtest": "量化回测",
    "operation.coverage_audit": "运行覆盖检查",
    "operation.intraday_audit": "运行分钟数据检查",
    "operation.runs": "查询运行记录",
    "operation.storage_review": "检查存储范围",
    "operation.storage_execute": "执行安全清理",
    "operation.export": "导出",
    "opend.title": "确认 OpenD 操作",
    "opend.message": "此操作可能连接 OpenD。",
    "opend.operation": "操作",
    "opend.host": "主机",
    "opend.port": "端口",
    "field.symbols": "标的",
    "field.code": "代码",
    "field.start_date": "开始日期",
    "field.end_date": "结束日期",
    "field.bootstrap_start_date": "初始开始日期",
    "field.calendar_market": "日历市场",
    "field.calendar_code": "日历代码",
    "field.scope": "范围",
    "field.market": "市场",
    "field.interval": "周期",
    "field.requested_session": "请求时段",
    "field.bar_session": "K 线时段",
    "field.session": "时段",
    "field.adjustment": "复权",
    "field.page_size": "每页行数",
    "field.max_retries": "最大重试次数",
    "field.retry_backoff": "重试退避（秒）",
    "field.force": "强制重采",
    "field.incremental": "增量模式",
    "field.status": "状态",
    "field.dataset": "数据集",
    "field.source": "数据源",
    "field.source_schema_version": "数据源模式版本",
    "field.confirmation": "精确确认文本",
    "field.cleanup_policy": "清理策略",
    "historical.plan": "本地生成计划",
    "historical.execute": "通过 OpenD 执行",
    "historical.plan_items": "回填计划项目",
    "calendar.local_query": "查询本地数据",
    "calendar.fetch": "从 OpenD 获取",
    "market.query": "查询本地数据",
    "inventory.inspect": "检查库存",
    "audit.run": "运行本地检查",
    "runs.refresh": "刷新运行记录",
    "storage.warning": "文件仅移动到保留的隔离区，不支持永久删除。",
    "storage.review": "检查范围",
    "storage.execute": "执行安全清理",
    "storage.plan_id": "已检查计划 ID",
    "storage.refusals": "拒绝原因",
    "storage.confirmation_help": "检查可执行计划后，请准确输入 PURGE <plan_id>。",
    "storage.policy.exact_scope": "精确范围清理",
    "storage.policy.superseded_only": "仅清理旧快照",
    "quant.dataset_path": "Research Dataset 目录",
    "quant.dataset_placeholder": "D:\\...\\multi-source-cross-day-dataset-<id>",
    "quant.dataset_help": "选择一个精确的已验证 Research Dataset artifact；不会自动选择 latest，也不会联网。",
    "quant.inspect": "验证数据集",
    "quant.browse": "浏览...",
    "quant.choose_dataset": "选择 Research Dataset 目录",
    "quant.builder_tab": "数据集构建",
    "quant.builder_symbol": "研究标的",
    "quant.builder_preset": "因子预设",
    "quant.builder_horizon": "未来周期（交易日）",
    "quant.builder_cohort": "研究数据标准",
    "quant.builder_preview": "检查构建条件",
    "quant.builder_prepare": "通过 OpenD 准备数据",
    "quant.builder_build": "构建数据集",
    "quant.builder_help": "先检查构建条件。需要时可显式通过 OpenD 采集研究专用的 10.9-mv-ts2 / RTH / NONE 数据；“构建数据集”本身完全本地执行，会生成并验证 Canonical 与 Research Dataset，然后自动载入新数据集。",
    "quant.feature_tab": "因子研究",
    "quant.backtest_tab": "策略回测",
    "quant.comparison_tab": "策略比较",
    "quant.common_features": "公共因子（逗号分隔）",
    "quant.add_strategy": "新增",
    "quant.remove_strategy": "移除",
    "quant.strategy_name": "策略名称",
    "quant.strategy_kind": "策略类型",
    "quant.feature_rule": "单因子规则",
    "quant.composite_rule": "组合规则",
    "quant.condition_match": "条件组合",
    "quant.match_all": "满足全部条件",
    "quant.match_any": "满足任一条件",
    "quant.add_condition": "新增条件",
    "quant.condition_columns": "因子 / 比较符 / 阈值（使用 Dataset 原始单位）",
    "quant.trend_feature": "趋势因子（GT）",
    "quant.trend_threshold": "趋势触发阈值（>）",
    "quant.reversion_feature": "均值回归因子（LT）",
    "quant.reversion_threshold": "均值回归触发阈值（<）",
    "quant.ridge_alpha": "Ridge 正则参数 alpha",
    "quant.ridge_threshold": "预测收益触发阈值（>）",
    "quant.train_periods": "最少训练期数",
    "quant.validation_periods": "每折验证期数",
    "quant.step_periods": "滚动步长期数",
    "quant.run_comparison": "比较策略",
    "quant.include_equity": "加入 K 线收盘估值",
    "quant.include_risk": "加入基准与风险",
    "quant.risk_results": "基准与风险",
    "quant.risk_help": "日收益取完整交易日收盘之间的变化，年化因子 252，无风险利率 0。n < 2 表示日收益观测不足，σ = 0 表示零波动，两种情况的 Sharpe 均不可计算。累计收益覆盖整个窗口。基准采用相同成本和价格口径，不含分红再投资。",
    "quant.benchmark_legend": "金线：所选曲线；灰线：采用相同成本的买入持有价格基准。",
    "summary.risk_report_id": "风险报告 ID",
    "columns.return_difference": "收益减去基准",
    "columns.annualized_volatility": "年化波动率",
    "columns.sharpe_ratio": "Sharpe（无风险利率 0）",
    "columns.daily_return_count": "日收益观测数 n",
    "columns.risk_status": "风险指标状态",
    "quant.collapse_inputs": "收起参数",
    "quant.expand_inputs": "展开参数",
    "quant.comparison_results": "比较结果",
    "quant.equity_ledger": "净值与账本",
    "quant.bar_equity": "K 线收盘净值",
    "quant.equity_help": "初始权益为 1.0，使用现金与小数份额。按记录的 K 线可知时间及成交事件更新估值，不推测 K 线内部价格路径。",
    "summary.equity_comparison_id": "净值比较 ID",
    "columns.bar_close_max_drawdown": "收盘估值最大回撤",
    "columns.timestamp": "时间（UTC）",
    "columns.event": "事件",
    "columns.cash": "现金",
    "columns.quantity": "份额",
    "columns.mark_price": "估值价格",
    "columns.market_value": "持仓市值",
    "columns.equity": "总权益",
    "columns.drawdown": "回撤",
    "columns.transaction_cost": "本次成本",
    "quant.comparison_help": "仅比较开发期验证结果，TEST 保持留出。规则使用的因子必须列入逗号分隔的公共因子列表，Ridge 也使用这组输入；期数按样本时间计数。展开参数后可继续编辑下一次比较。",
    "quant.open_experiment": "打开实验",
    "quant.save_experiment": "保存实验",
    "quant.replay_experiment": "重放核验",
    "quant.replay_relocated": "换目录重放",
    "quant.snapshot_loaded": "已保留运行；尚未核验重放",
    "quant.replay_verified": "完整重放结果一致",
    "quant.experiment_help": "保存上次成功运行。打开可离线查看，重放将核对完整结果。",
    "quant.diagnose_strategy": "策略诊断",
    "quant.diagnostics_title": "参数与成本诊断",
    "quant.diagnostics_help": "从当前表单选择一个策略，显式填写最多两个参数轴的取值及每边交易成本。最多 64 次评估，共用开发期验证窗口，TEST 保持留出。",
    "quant.no_axis": "不设置参数轴",
    "quant.condition_axis": "条件阈值",
    "quant.first_axis": "第一个参数轴",
    "quant.second_axis": "第二个参数轴",
    "quant.axis_values": "取值，以逗号分隔",
    "quant.cost_scenarios": "佣金/滑点（bps），如 0/0,10/5",
    "quant.diagnostics_count": "评估次数",
    "quant.run_diagnostics": "运行诊断",
    "quant.diagnostics_results": "全部候选",
    "quant.fold_contributions": "各折贡献",
    "quant.diagnostic_candidate": "候选 · 佣金/滑点",
    "quant.diagnostic_results_help": "按输入顺序展示，收益变化与同一参数组合的首个成本场景比较。选择候选可查看对应成本组、净值与折贡献；保存和重放包含全部候选。",
    "quant.fold_help": "净现金贡献来自初始权益为 1 的连续账户，交易归属产生信号的验证折，跨折平仓也不转移归属。无交易的折仍保留，各折贡献之和在记账容差内等于最终净收益。",
    "summary.evaluation_count": "评估次数",
    "summary.variant_count": "参数组合数",
    "summary.cost_scenario_count": "成本场景数",
    "columns.diagnostic_candidate": "候选",
    "columns.parameters": "参数取值",
    "columns.commission_bps": "佣金（bps）",
    "columns.slippage_bps": "滑点（bps）",
    "columns.return_change_from_first_cost": "较首个成本的收益变化",
    "columns.fold_index": "验证折",
    "columns.validation_start_time": "验证起点（UTC）",
    "columns.validation_end_time": "验证终点（UTC）",
    "columns.validation_sample_count": "验证样本数",
    "columns.cash_contribution": "净现金贡献",
    "operation.strategy_diagnostics": "策略诊断",
    "summary.comparison_id": "比较 ID",
    "summary.fold_count": "验证折数",
    "summary.common_validation_rows": "共同验证样本",
    "summary.held_out_test_rows": "留出 TEST 样本",
    "columns.strategy": "策略",
    "columns.trade_count": "交易数",
    "columns.total_return": "净收益",
    "columns.gross_total_return": "毛收益",
    "columns.realized_max_drawdown": "已实现最大回撤",
    "columns.win_rate": "胜率",
    "columns.profit_factor": "盈利因子",
    "columns.overlap_skipped_count": "重叠跳过数",
    "columns.exposure": "持仓暴露",
    "operation.strategy_comparison": "策略比较",
    "quant.label": "标签",
    "quant.split": "数据分区",
    "quant.quantiles": "分位数组数",
    "quant.run_feature": "分析因子",
    "quant.feature_results": "因子指标",
    "quant.signal_feature": "信号因子",
    "quant.comparator": "比较条件",
    "quant.threshold": "阈值",
    "quant.return_label": "执行收益标签",
    "quant.commission_bps": "单边手续费（bps）",
    "quant.slippage_bps": "单边滑点（bps）",
    "quant.run_backtest": "运行回测",
    "quant.equity_curve": "标准化权益曲线",
    "quant.no_backtest": "运行一次回测后显示权益曲线",
    "quant.trades": "交易明细",
    "summary.dataset_id": "数据集 ID",
    "summary.symbols": "标的",
    "summary.rows": "总行数",
    "summary.features": "因子数",
    "summary.labels": "标签数",
    "summary.train_rows": "训练集",
    "summary.validation_rows": "验证集",
    "summary.test_rows": "测试集",
    "summary.artifact_status": "Artifact",
    "summary.split": "分区",
    "summary.label": "标签",
    "summary.feature_count": "因子数",
    "summary.sample_count": "样本数",
    "summary.best_feature": "最佳 |RankIC|",
    "summary.best_rank_ic": "RankIC",
    "summary.quantiles": "分位数组",
    "summary.backtest_id": "回测 ID",
    "summary.trade_count": "交易数",
    "summary.signal_count": "信号数",
    "summary.total_return": "总收益",
    "summary.max_drawdown": "最大回撤",
    "summary.win_rate": "胜率",
    "summary.avg_trade_return": "平均单笔",
    "summary.profit_factor": "盈亏比",
    "summary.exposure": "持仓暴露",
    "summary.research_schema": "研究数据版本",
    "summary.symbol": "标的",
    "summary.interval": "周期",
    "summary.preset": "因子预设",
    "summary.horizon": "未来周期",
    "summary.trading_dates": "交易日数",
    "summary.anchor_dates": "样本锚点数",
    "summary.missing_research_dates": "缺失研究数据日期",
    "summary.feature_window_bars": "特征窗口",
    "summary.train_end": "训练集结束",
    "summary.validation_end": "验证集结束",
    "summary.test_end": "测试集结束",
    "summary.build_ready": "可构建",
    "summary.canonical_build_id": "Canonical 构建 ID",
    "summary.canonical_rows": "Canonical 行数",
    "summary.dataset_status": "数据集状态",
    "summary.dataset_rows": "数据集行数",
    "summary.dataset_path": "数据集路径",
    "summary.research_data_prepare": "研究数据准备",
    "summary.successful_items": "成功项目",
    "summary.failed_items": "失败项目",
    "columns.calendar_profile": "交易日时段",
    "columns.research_data": "研究数据",
    "columns.role": "研究角色",
    "columns.feature_name": "因子",
    "columns.sample_count": "样本数",
    "columns.pearson_ic": "Pearson IC",
    "columns.rank_ic": "Rank IC",
    "columns.top_bottom_spread": "头尾分组差",
    "columns.feature_mean": "因子均值",
    "columns.feature_std": "因子标准差",
    "columns.signal_time": "信号时间",
    "columns.entry_time": "入场时间",
    "columns.exit_time": "离场时间",
    "columns.signal_value": "信号值",
    "columns.gross_return": "毛收益",
    "columns.net_return": "净收益",
    "columns.equity_after": "交易后权益",
    "columns.code": "代码",
    "columns.symbol": "标的",
    "columns.trade_date": "交易日期",
    "columns.requested_trade_date": "请求交易日期",
    "columns.interval": "周期",
    "columns.session": "时段",
    "columns.adjustment": "复权",
    "columns.state": "状态",
    "columns.page": "页码",
    "columns.market": "市场",
    "columns.date": "日期",
    "columns.trade_date_type": "交易日类型",
    "columns.ingestion_run_id": "采集运行 ID",
    "columns.source_state": "数据源状态",
    "columns.audit_status": "检查状态",
    "columns.boundary_evaluated": "边界已评估",
    "columns.internal_gap_count": "内部缺口",
    "columns.physical_scope_status": "物理范围",
    "columns.symbols": "标的",
    "columns.dates": "日期",
    "columns.affected_rows": "影响行数",
    "columns.raw_bytes": "Raw 字节数",
    "columns.curated_bytes": "Curated 字节数",
    "columns.raw_path": "Raw 路径",
    "columns.curated_path": "Curated 路径",
    "columns.requested_session": "请求时段",
    "columns.source_schema_version": "数据源模式版本",
    "columns.superseded_run_id": "旧快照运行 ID",
    "columns.retained_run_id": "保留运行 ID",
    "columns.superseded_ingested_at": "旧快照采集时间",
    "columns.retained_ingested_at": "保留快照采集时间",
}

EN.update({
    "quant.intraday_tab": "Intraday", "quant.intraday_build": "Build & save intraday data",
    "quant.intraday_open": "Open intraday data", "quant.intraday_stride": "Observation stride (bars)",
    "quant.intraday_horizon": "Training target bars (blank: off)",
    "quant.intraday_observations": "Observations", "quant.intraday_path": "Absolute intraday JSON file path",
    "quant.intraday_help": "Same-session Features, complete price history and independent training targets. Warmup restarts each day. Missing targets retain observations. Times below are UTC. Source preparation is available in Dataset Builder.",
    "summary.intraday_data_id": "Intraday data ID", "summary.intraday_prices": "Price bars",
    "summary.intraday_observations": "Observations", "summary.intraday_ready": "Ready observations",
    "summary.intraday_complete_targets": "Complete targets", "summary.intraday_incomplete_targets": "Incomplete targets",
    "summary.intraday_missing_prices": "Missing price bars", "columns.decision_time": "Decision (UTC)",
    "columns.target_status": "Training target", "columns.target_value": "Target return",
    "columns.intraday_observations": "Observations", "columns.reason": "Reason",
})
ZH_CN.update({
    "quant.intraday_tab": "日内研究", "quant.intraday_build": "构建并保存日内数据",
    "quant.intraday_open": "打开日内数据", "quant.intraday_stride": "观察步长（bar）",
    "quant.intraday_horizon": "训练目标 bar 数（留空关闭）",
    "quant.intraday_observations": "查看观察", "quant.intraday_path": "日内 JSON 文件的绝对路径",
    "quant.intraday_help": "同日特征、完整价格流与独立训练目标。每天重新预热；目标不完整仍保留观察。下表时间为 UTC。可在“构建数据集”中准备研究来源数据。",
    "summary.intraday_data_id": "日内数据 ID", "summary.intraday_prices": "价格 bar 数",
    "summary.intraday_observations": "观察数", "summary.intraday_ready": "可用观察",
    "summary.intraday_complete_targets": "完整目标", "summary.intraday_incomplete_targets": "不完整目标",
    "summary.intraday_missing_prices": "缺价 bar 数", "columns.decision_time": "决策时间（UTC）",
    "columns.target_status": "训练目标状态", "columns.target_value": "目标收益",
    "columns.intraday_observations": "观察数", "columns.reason": "原因",
})

EN.update({
    "quant.intraday_data_tab": "Data", "quant.intraday_execution_tab": "Execution V2",
    "quant.intraday_open_first": "Open intraday data in the Data tab first.",
    "quant.intraday_entry_delay": "Entry delay after open (min)",
    "quant.intraday_stop_new": "Stop entry before close (min)",
    "quant.intraday_flatten": "Flatten before close (min)",
    "quant.intraday_max_hold": "Maximum hold (price bars)",
    "quant.intraday_result_data": "Result data ID", "quant.intraday_ledger": "Bar ledger (UTC)",
    "quant.intraday_daily": "Daily settlement", "summary.final_cash": "Final cash",
    "summary.observed_max_drawdown": "Observed maximum drawdown",
    "columns.phase": "Event phase", "columns.action": "Action", "columns.slot": "Price bar slot",
    "columns.held_bars": "Held price bars", "columns.exit_reason": "Exit reason",
    "columns.entry_fill_price": "Entry fill", "columns.exit_fill_price": "Exit fill",
    "columns.cash_before": "Cash before", "columns.cash_after": "Cash after",
    "columns.commission_total": "Commission", "columns.slippage_total": "Slippage cost",
    "columns.trading_day": "Trading day", "columns.cash_open": "Opening cash", "columns.cash_close": "Closing cash",
    "columns.return": "Day return", "operation.intraday_backtest": "Intraday execution V2",
})
ZH_CN.update({
    "quant.intraday_data_tab": "数据", "quant.intraday_execution_tab": "执行 V2",
    "quant.intraday_open_first": "请先在“数据”页打开日内数据。",
    "quant.intraday_entry_delay": "开盘后禁入（分钟）",
    "quant.intraday_stop_new": "收盘前停止入场（分钟）",
    "quant.intraday_flatten": "收盘前清仓（分钟）",
    "quant.intraday_max_hold": "最长持有（价格 bar）",
    "quant.intraday_result_data": "结果数据 ID", "quant.intraday_ledger": "逐 bar 账本（UTC）",
    "quant.intraday_daily": "每日结算", "summary.final_cash": "最终现金",
    "summary.observed_max_drawdown": "观察点最大回撤",
    "columns.phase": "事件阶段", "columns.action": "操作", "columns.slot": "价格 bar 序号",
    "columns.held_bars": "持有 bar 数", "columns.exit_reason": "离场原因",
    "columns.entry_fill_price": "入场成交价", "columns.exit_fill_price": "离场成交价",
    "columns.cash_before": "交易前现金", "columns.cash_after": "交易后现金",
    "columns.commission_total": "手续费", "columns.slippage_total": "滑点成本",
    "columns.trading_day": "交易日期", "columns.cash_open": "日初现金", "columns.cash_close": "日末现金",
    "columns.return": "日收益率", "operation.intraday_backtest": "日内执行 V2",
})

EN.update({
    "quant.intraday_research_tab": "Development research", "quant.intraday_settings": "Research settings",
    "quant.intraday_computed": "Computed", "quant.intraday_replay_pending": "Replaying", "quant.intraday_replay_failed": "Latest replay failed",
    "quant.intraday_research_help": "Confirm explicit trading-day boundaries and costs. Expanding walk-forward uses TRAIN + VALIDATION; TEST remains held out. Every candidate uses the same READY observations and price grid.",
    "quant.intraday_train_end": "TRAIN last day", "quant.intraday_validation_end": "VALIDATION last day",
    "quant.intraday_test_end": "TEST last day", "quant.intraday_train_days": "Minimum training days",
    "quant.intraday_validation_days": "Validation days per fold", "quant.intraday_step_days": "Step (trading days)",
    "quant.intraday_apply_settings": "Keep settings", "quant.intraday_result_view": "Result view",
    "quant.intraday_overview": "Comparison", "quant.intraday_models": "Fold models & scalers",
    "quant.intraday_predictions": "All READY predictions", "quant.intraday_contributions": "Fold cash contributions",
    "quant.intraday_equity_legend": "Daily equity · gold: candidate · blue: first eligible entry to EOD benchmark",
    "summary.intraday_eval_days": "Evaluated days", "summary.intraday_verification": "Verification",
    "columns.cost_return_change": "Return change vs first cost", "columns.training_count": "Training rows",
    "columns.alpha": "Ridge alpha", "columns.coefficient": "Coefficient", "columns.mean": "Training mean",
    "columns.scale": "Training scale", "columns.validation_days": "Validation dates",
    "columns.benchmark_return": "Daily benchmark return", "columns.observed_max_drawdown": "Observed max drawdown",
    "columns.feature": "Feature", "columns.intercept": "Intercept", "columns.score": "Score", "columns.target": "Target position",
    "columns.mae": "Target MAE", "columns.rmse": "Target RMSE", "columns.r2": "Target R²",
    "operation.intraday_research": "Intraday development research", "operation.intraday_experiment_save": "Save intraday experiment",
    "operation.intraday_experiment_open": "Open intraday experiment", "operation.intraday_experiment_replay": "Replay intraday experiment",
})
ZH_CN.update({
    "quant.intraday_research_tab": "开发期研究", "quant.intraday_settings": "研究设置",
    "quant.intraday_computed": "已计算", "quant.intraday_replay_pending": "正在重放", "quant.intraday_replay_failed": "最近重放失败",
    "quant.intraday_research_help": "请确认交易日边界与成本。扩展滚动验证使用 TRAIN + VALIDATION，TEST 保持留出。所有候选使用共同的可用观察与完整价格流。",
    "quant.intraday_train_end": "TRAIN 最后交易日", "quant.intraday_validation_end": "VALIDATION 最后交易日",
    "quant.intraday_test_end": "TEST 最后交易日", "quant.intraday_train_days": "最少训练交易日",
    "quant.intraday_validation_days": "每折验证交易日", "quant.intraday_step_days": "推进步长（交易日）",
    "quant.intraday_apply_settings": "保留设置", "quant.intraday_result_view": "结果视图",
    "quant.intraday_overview": "比较总览", "quant.intraday_models": "逐折模型与标准化",
    "quant.intraday_predictions": "全部可用观察预测", "quant.intraday_contributions": "逐折现金贡献",
    "quant.intraday_equity_legend": "日净值 · 金色：候选 · 蓝色：首个可入场观察至收盘基准",
    "summary.intraday_eval_days": "评估交易日", "summary.intraday_verification": "验证状态",
    "columns.cost_return_change": "相对首组成本收益变化", "columns.training_count": "训练行数",
    "columns.alpha": "Ridge alpha", "columns.coefficient": "系数", "columns.mean": "训练均值",
    "columns.scale": "训练尺度", "columns.validation_days": "验证交易日",
    "columns.benchmark_return": "日内基准收益", "columns.observed_max_drawdown": "观察到的最大回撤",
    "columns.feature": "特征", "columns.intercept": "截距", "columns.score": "分值", "columns.target": "目标仓位",
    "columns.mae": "目标 MAE", "columns.rmse": "目标 RMSE", "columns.r2": "目标 R²",
    "operation.intraday_research": "日内开发期研究", "operation.intraday_experiment_save": "保存日内实验",
    "operation.intraday_experiment_open": "打开日内实验", "operation.intraday_experiment_replay": "重放日内实验",
})

EN.update({
    "quant.intraday_final_tab": "Freeze / TEST", "quant.intraday_development_candidate": "Development candidate",
    "quant.intraday_freeze": "Freeze selected", "quant.intraday_frozen": "Frozen",
    "quant.intraday_final_help": "Save the development experiment before freezing. Costs below are commission/slippage. Ridge fits TRAIN + VALIDATION once; rules need no fit. TEST starts with independent capital.",
    "quant.intraday_selection_open": "Open selection", "quant.intraday_selection_save": "Save selection",
    "quant.intraday_selection_replay": "Replay selection", "quant.intraday_test_run": "Run frozen TEST",
    "quant.intraday_test_open": "Open TEST", "quant.intraday_test_save": "Save TEST",
    "quant.intraday_test_replay": "Replay TEST", "quant.intraday_final_model": "Final model & scaler",
    "quant.intraday_locations": "Source locations", "quant.intraday_locations_clear": "Use recorded locations",
    "quant.intraday_locations_help": "Optional relocated files. Blank uses the frozen location. Both identities must match. Choosing a file does not run TEST or replay; use the main action buttons afterward.",
    "quant.intraday_source_override": "Development experiment file (optional)",
    "quant.intraday_data_override": "Intraday data file (optional)",
    "quant.intraday_locations_active": "Explicit source locations are active. Review them in Source locations.",
    "summary.intraday_selection_proof": "Selection verification", "summary.intraday_test_proof": "TEST verification",
    "operation.intraday_selection_freeze": "Freeze intraday candidate",
    "operation.intraday_selection_open": "Open intraday selection", "operation.intraday_selection_save": "Save intraday selection",
    "operation.intraday_selection_replay": "Replay intraday selection", "operation.intraday_test_run": "Run frozen intraday TEST",
    "operation.intraday_test_open": "Open intraday TEST", "operation.intraday_test_save": "Save intraday TEST",
    "operation.intraday_test_replay": "Replay complete intraday TEST",
})
ZH_CN.update({
    "quant.intraday_final_tab": "冻结 / TEST", "quant.intraday_development_candidate": "开发期候选",
    "quant.intraday_freeze": "冻结所选候选", "quant.intraday_frozen": "已冻结",
    "quant.intraday_final_help": "冻结前请先保存开发实验。下方成本为手续费/滑点。Ridge 使用 TRAIN + VALIDATION 拟合一次；规则无需拟合。TEST 使用独立初始资金。",
    "quant.intraday_selection_open": "打开冻结记录", "quant.intraday_selection_save": "保存冻结记录",
    "quant.intraday_selection_replay": "重放冻结来源", "quant.intraday_test_run": "运行冻结 TEST",
    "quant.intraday_test_open": "打开 TEST", "quant.intraday_test_save": "保存 TEST",
    "quant.intraday_test_replay": "完整重放 TEST", "quant.intraday_final_model": "最终模型与标准化",
    "quant.intraday_locations": "来源位置", "quant.intraday_locations_clear": "使用记录的位置",
    "quant.intraday_locations_help": "可选迁移后的文件，留空使用冻结记录中的位置，两个身份均须匹配。选择文件不会运行 TEST 或重放；完成后使用主页面的操作按钮。",
    "quant.intraday_source_override": "开发实验文件（可选）", "quant.intraday_data_override": "日内数据文件（可选）",
    "quant.intraday_locations_active": "已启用显式来源位置，可在“来源位置”中查看。",
    "summary.intraday_selection_proof": "冻结来源验证", "summary.intraday_test_proof": "TEST 验证",
    "operation.intraday_selection_freeze": "冻结日内候选",
    "operation.intraday_selection_open": "打开日内冻结记录", "operation.intraday_selection_save": "保存日内冻结记录",
    "operation.intraday_selection_replay": "重放日内冻结来源", "operation.intraday_test_run": "运行冻结日内 TEST",
    "operation.intraday_test_open": "打开日内 TEST", "operation.intraday_test_save": "保存日内 TEST",
    "operation.intraday_test_replay": "完整重放日内 TEST",
})

EN.update({
    "quant.performance": "Trade performance", "quant.performance_exit": "P&L by exit reason",
    "quant.performance_entry": "P&L by entry hour", "quant.performance_day": "P&L by day",
    "quant.performance_note": "Derived from recorded trades; not a replay. Cash P&L uses initial cash = 1. Entry buckets are minutes since session open; exposure includes all evaluated session minutes.",
    "columns.metric": "Metric", "columns.value": "Value", "columns.unit": "Unit", "columns.group": "Group",
    "columns.unavailable_reason": "Unavailable reason", "columns.market_pnl": "Market P&L",
    "columns.net_cash_pnl": "Net cash P&L", "columns.holding_minutes": "Holding minutes",
    "performance.trade_count": "Trades", "performance.winning_trades": "Winning trades",
    "performance.losing_trades": "Losing trades", "performance.breakeven_trades": "Breakeven trades",
    "performance.win_rate": "Win rate", "performance.mean_trade_return": "Mean trade return",
    "performance.profit_factor": "Profit factor", "performance.payoff_ratio": "Payoff ratio",
    "performance.mean_holding_minutes": "Mean hold (min)", "performance.mean_held_bars": "Mean hold (bars)",
    "performance.exposure_ratio": "Time exposure", "performance.evaluated_days": "Evaluated days",
    "performance.cash_only_days": "Cash-only days", "performance.market_pnl": "Market P&L",
    "performance.commission_total": "Commission", "performance.slippage_total": "Slippage cost",
    "performance.net_cash_pnl": "Net cash P&L", "performance.COUNT": "Count", "performance.NUMBER": "Ratio",
    "performance.RATIO": "%", "performance.MINUTES": "Minutes", "performance.BARS": "Bars",
    "performance.INITIAL_CASH_UNITS": "Initial cash = 1", "performance.NO_TRADES": "No trades",
    "performance.NO_LOSING_TRADES": "No losing trades", "performance.NEEDS_WIN_AND_LOSS": "Needs wins + losses",
    "performance.NUMERIC_OVERFLOW": "Numeric overflow", "performance.UNAVAILABLE": "Unavailable",
    "performance.EOD": "End of day", "performance.MAX_HOLD": "Maximum hold", "performance.TARGET_FLAT": "Flat signal",
})
ZH_CN.update({
    "quant.performance": "交易绩效", "quant.performance_exit": "按退出原因归因",
    "quant.performance_entry": "按入场时段归因", "quant.performance_day": "逐日盈亏归因",
    "quant.performance_note": "由已记录交易计算，不代表回放验证。现金盈亏以初始资金 1 为单位。入场时段为开盘后的分钟数；持仓占比包含全部评估交易时段。",
    "columns.metric": "指标", "columns.value": "数值", "columns.unit": "单位", "columns.group": "分组",
    "columns.unavailable_reason": "不可用原因", "columns.market_pnl": "价格变动盈亏",
    "columns.net_cash_pnl": "净现金盈亏", "columns.holding_minutes": "持仓分钟数",
    "performance.trade_count": "交易次数", "performance.winning_trades": "盈利次数",
    "performance.losing_trades": "亏损次数", "performance.breakeven_trades": "持平次数",
    "performance.win_rate": "胜率", "performance.mean_trade_return": "平均逐笔收益率",
    "performance.profit_factor": "盈利因子", "performance.payoff_ratio": "平均盈亏比",
    "performance.mean_holding_minutes": "平均持仓分钟", "performance.mean_held_bars": "平均持仓K线数",
    "performance.exposure_ratio": "持仓时间占比", "performance.evaluated_days": "评估交易日数",
    "performance.cash_only_days": "全日空仓天数", "performance.market_pnl": "价格变动盈亏",
    "performance.commission_total": "手续费", "performance.slippage_total": "滑点成本",
    "performance.net_cash_pnl": "净现金盈亏", "performance.COUNT": "次数", "performance.NUMBER": "比值",
    "performance.RATIO": "%", "performance.MINUTES": "分钟", "performance.BARS": "K线数",
    "performance.INITIAL_CASH_UNITS": "初始资金 = 1", "performance.NO_TRADES": "无交易",
    "performance.NO_LOSING_TRADES": "无亏损交易", "performance.NEEDS_WIN_AND_LOSS": "需要盈利和亏损样本",
    "performance.NUMERIC_OVERFLOW": "数值溢出", "performance.UNAVAILABLE": "不可用",
    "performance.EOD": "日终强平", "performance.MAX_HOLD": "持仓期限", "performance.TARGET_FLAT": "空仓信号",
})

EN.update({
    "quant.execution_scenarios": "Execution scenarios", "quant.execution_scenario": "Execution scenario",
    "quant.scenarios_editor_help": "Compare the current strategies and day split using explicit execution policies. Enter costs for each scenario; new scenarios copy the selected policy for editing. All evaluations stay in development.",
    "quant.scenario_name_prefix": "Scenario", "quant.scenario_name": "Scenario name",
    "quant.scenario_add": "Add", "quant.scenario_remove": "Remove",
    "quant.scenarios_evaluation_limit": "evaluations (maximum 64)", "quant.scenarios_run": "Run scenarios",
    "quant.scenarios_save": "Save all scenarios", "quant.scenarios_replay": "Replay all scenarios",
    "quant.scenario_export": "Export selected scenario",
    "quant.scenario_exported": "This scenario is saved as a development experiment. Select its candidate in Freeze / TEST.",
    "quant.scenario_export_required": "Export this scenario as a development experiment before freezing its candidate. Saving the collection retains all scenarios.",
    "quant.scenarios_comparison_note": "All scenarios and strategies remain in input order. Return change compares the same strategy with the first scenario, in percentage points. Detail views and the chart show the selected scenario and candidate.",
    "summary.intraday_scenarios": "Scenarios", "columns.scenario": "Scenario",
    "columns.entry_delay_minutes": "Entry delay (min)", "columns.stop_new_minutes": "Stop entry (min before close)",
    "columns.flatten_minutes": "Flatten (min before close)", "columns.max_hold_bars": "Maximum hold (bars)",
    "columns.scenario_return_change": "Return change (pp)",
    "operation.intraday_scenarios": "Evaluate intraday execution scenarios",
    "operation.intraday_scenarios_save": "Save all intraday scenarios",
    "operation.intraday_scenarios_replay": "Replay all intraday scenarios",
    "operation.intraday_scenario_export": "Export selected intraday scenario",
})
ZH_CN.update({
    "quant.execution_scenarios": "执行情景", "quant.execution_scenario": "执行情景",
    "quant.scenarios_editor_help": "沿用当前策略和交易日切分，比较明确填写的执行政策。每个情景需填写成本；新增情景会复制所选政策供修改。全部评估只使用开发期。",
    "quant.scenario_name_prefix": "情景", "quant.scenario_name": "情景名称",
    "quant.scenario_add": "添加", "quant.scenario_remove": "移除",
    "quant.scenarios_evaluation_limit": "次评估（最多 64）", "quant.scenarios_run": "运行情景",
    "quant.scenarios_save": "保存全部情景", "quant.scenarios_replay": "重放全部情景",
    "quant.scenario_export": "导出所选情景",
    "quant.scenario_exported": "此情景已保存为开发实验，可前往“冻结 / TEST”选择并冻结其中的候选。",
    "quant.scenario_export_required": "冻结候选前，请将此情景导出为开发实验。保存情景集合会保留全部情景。",
    "quant.scenarios_comparison_note": "全部情景和策略保持输入顺序。收益变化以百分点表示，相对首个情景中的同一策略计算。明细和图表显示当前所选情景与候选。",
    "summary.intraday_scenarios": "情景数", "columns.scenario": "情景",
    "columns.entry_delay_minutes": "开盘后禁入（分钟）", "columns.stop_new_minutes": "收盘前停止入场（分钟）",
    "columns.flatten_minutes": "收盘前清仓（分钟）", "columns.max_hold_bars": "最长持有（bar）",
    "columns.scenario_return_change": "收益变化（百分点）",
    "operation.intraday_scenarios": "评估日内执行情景", "operation.intraday_scenarios_save": "保存全部日内情景",
    "operation.intraday_scenarios_replay": "重放全部日内情景", "operation.intraday_scenario_export": "导出所选日内情景",
})

EN.update({
    "quant.intraday_saved_comparison_tab": "Saved A/B",
    "quant.saved_comparison_help": "Open two saved development, diagnostics or TEST experiments, then choose their cost and candidate indices (starting at 0). Export a scenario collection to an ordinary development experiment first. Changing these inputs keeps the previous result until Compare succeeds.",
    "quant.saved_open_left": "Open A", "quant.saved_open_right": "Open B",
    "quant.saved_choose_file": "Choose a saved experiment.",
    "quant.saved_cost_index": "Cost index", "quant.saved_candidate_index": "Candidate index",
    "quant.saved_compare": "Compare saved A/B", "quant.saved_bound_sources": "Sources captured for the displayed result",
    "quant.saved_experiment_id": "Experiment ID", "quant.saved_candidate_id": "Candidate ID", "quant.saved_data_id": "Data ID",
    "quant.saved_evidence_note": "Values come from saved records and recorded-ledger attribution. This comparison does not establish replay verification.",
    "quant.saved_units_note": "Differences are B minus A. Return ratios use percentages; their differences use percentage points (pp). Other metrics retain their original unit.",
    "quant.saved_strategy_metrics": "Strategy metrics", "quant.saved_benchmark_metrics": "Benchmark metrics",
    "quant.saved_config_differences": "Configuration differences", "quant.saved_basis_checks": "Basis checks",
    "quant.saved_compact_values": "Long evidence arrays and objects show [item count] or {field count}, followed by a SHA-256 prefix. Basis checks compare the complete original values.",
    "quant.saved_no_differences": "The selected configurations match.",
    "columns.compare_left": "A", "columns.compare_right": "B", "columns.compare_left_unit": "A unit",
    "columns.compare_right_unit": "B unit", "columns.compare_delta": "B − A", "columns.compare_delta_unit": "Delta unit",
    "columns.compare_left_reason": "A unavailable", "columns.compare_right_reason": "B unavailable",
    "columns.compare_delta_reason": "Delta unavailable", "columns.compare_left_evidence": "A evidence",
    "columns.compare_right_evidence": "B evidence", "columns.compare_field": "Field", "columns.compare_matches": "Basis matches",
    "comparison.COMPARABLE_DEV": "The saved development records share the evaluation basis. Neutral B − A differences are available.",
    "quant.saved_notice_BASIS_MISMATCH": "The recorded evaluation bases differ. Values remain side by side; differences are unavailable. Inspect Basis checks for the specific fields.",
    "quant.saved_notice_TEST_DESCRIPTIVE_ONLY": "This comparison includes TEST. It is descriptive only; every numerical difference is unavailable.",
    "comparison.BASIS_MISMATCH": "Basis differs", "comparison.TEST_DESCRIPTIVE_ONLY": "TEST: descriptive",
    "comparison.LEFT_UNAVAILABLE": "A unavailable", "comparison.RIGHT_UNAVAILABLE": "B unavailable",
    "comparison.BOTH_UNAVAILABLE": "A and B unavailable", "comparison.NOT_APPLICABLE": "Not applicable",
    "comparison.UNAVAILABLE_STATISTIC": "Statistic unavailable", "comparison.ZERO_VOLATILITY": "Zero volatility",
    "comparison.INSUFFICIENT_DAILY_RETURNS": "Too few daily returns", "comparison.NO_COMPLETE_TARGETS": "No complete targets",
    "comparison.UNSUPPORTED_EXECUTION_OR_COST_VERSION": "Unsupported execution/cost version",
    "comparison.RECORDED_CASH_RECONCILIATION_FAILED": "Recorded cash does not reconcile",
    "comparison.RECORDED": "Saved record", "comparison.RECORDED_LEDGER_DERIVATION": "Ledger attribution",
    "comparison.RECORDED_DIFFERENCE": "Saved-value difference", "comparison.PERCENTAGE_POINTS": "pp",
    "comparison.MATCH": "Match", "comparison.DIFFERENT": "Different", "comparison.MISSING": "Not present",
    "comparison.unnamed": "Unnamed", "comparison.candidate": "Strategy", "comparison.benchmark": "Benchmark",
    "comparison.INTRADAY_COMPARISON": "Development comparison", "comparison.INTRADAY_DIAGNOSTICS": "Development diagnostics",
    "comparison.INTRADAY_TEST": "Frozen TEST", "comparison.initial_cash": "Initial cash", "comparison.final_cash": "Final cash",
    "comparison.mean_daily_return": "Mean daily return", "comparison.return_count": "Daily returns",
    "comparison.prediction_count": "Predictions", "comparison.complete_target_count": "Complete targets",
    "comparison.evaluation_scope": "Evaluation scope", "comparison.data_id": "Data ID", "comparison.symbol": "Symbol",
    "comparison.interval": "Interval", "comparison.target_horizon_bars": "Target horizon (bars)", "comparison.split": "Trading-day split",
    "comparison.session_clocks": "Session clocks", "comparison.price_evidence_id": "Price evidence ID",
    "comparison.raw_prices": "Raw price sequence", "comparison.decision_identity": "Decision identity keys",
    "comparison.development_folds": "Development folds", "comparison.event_order": "Event order",
    "comparison.strategy_risk": "Strategy risk definition", "comparison.benchmark_risk": "Benchmark risk definition",
    "comparison.benchmark_definition": "Benchmark definition", "comparison.performance_derivation": "Attribution definition",
    "comparison.feature_fields": "Features and order", "comparison.strategy.name": "Strategy name",
    "comparison.strategy.kind": "Strategy kind", "comparison.strategy.alpha": "Ridge alpha",
    "comparison.strategy.threshold": "Strategy threshold", "comparison.strategy.signal_field": "Rule feature",
    "comparison.strategy.comparator": "Rule comparator", "comparison.strategy.conditions": "Rule conditions",
    "comparison.strategy.match": "Rule combination", "comparison.execution_policy.entry_delay_minutes": "Entry delay (min)",
    "comparison.execution_policy.stop_new_minutes": "Stop entry before close (min)",
    "comparison.execution_policy.flatten_minutes": "Flatten before close (min)",
    "comparison.execution_policy.max_hold_bars": "Maximum hold (bars)",
    "comparison.execution_policy.commission_bps": "Commission (bps/side)",
    "comparison.execution_policy.slippage_bps": "Slippage (bps/side)",
    "comparison.walk_forward": "Walk-forward plan", "comparison.walk_forward.minimum_train_days": "Minimum train days",
    "comparison.walk_forward.validation_days": "Validation days", "comparison.walk_forward.step_days": "Step days",
    "operation.intraday_compare_open_left": "Open saved intraday A", "operation.intraday_compare_open_right": "Open saved intraday B",
    "operation.intraday_compare_saved": "Compare saved intraday experiments",
})
ZH_CN.update({
    "quant.intraday_saved_comparison_tab": "已存 A/B 对比",
    "quant.saved_comparison_help": "打开两份已保存的开发、诊断或 TEST 实验，再选择成本组与候选索引（从 0 开始）。情景集合需先导出为普通开发实验。修改输入后，页面保留上次成功的结果，直到重新比较成功。",
    "quant.saved_open_left": "打开 A", "quant.saved_open_right": "打开 B",
    "quant.saved_choose_file": "请选择已保存的实验。",
    "quant.saved_cost_index": "成本组索引", "quant.saved_candidate_index": "候选索引",
    "quant.saved_compare": "比较已存 A/B", "quant.saved_bound_sources": "当前结果所绑定的来源",
    "quant.saved_experiment_id": "实验 ID", "quant.saved_candidate_id": "候选 ID", "quant.saved_data_id": "数据 ID",
    "quant.saved_evidence_note": "数值来自已保存记录及其账本归因；此对比不表示已通过重放验证。",
    "quant.saved_units_note": "差值按 B 减 A 计算。收益率显示为百分数，其差值使用百分点（pp）；其他指标沿用原单位。",
    "quant.saved_strategy_metrics": "策略指标", "quant.saved_benchmark_metrics": "基准指标",
    "quant.saved_config_differences": "配置差异", "quant.saved_basis_checks": "比较基础检查",
    "quant.saved_compact_values": "较长证据数组与对象显示为 [条目数] 或 {字段数}，后接 SHA-256 摘要前缀。比较基础检查仍使用完整原始值。",
    "quant.saved_no_differences": "所选配置一致。",
    "columns.compare_left": "A", "columns.compare_right": "B", "columns.compare_left_unit": "A 单位",
    "columns.compare_right_unit": "B 单位", "columns.compare_delta": "B − A", "columns.compare_delta_unit": "差值单位",
    "columns.compare_left_reason": "A 不可用原因", "columns.compare_right_reason": "B 不可用原因",
    "columns.compare_delta_reason": "差值不可用原因", "columns.compare_left_evidence": "A 来源",
    "columns.compare_right_evidence": "B 来源", "columns.compare_field": "字段", "columns.compare_matches": "基础一致",
    "comparison.COMPARABLE_DEV": "两份已保存开发记录的评估基础一致，可查看中性的 B − A 差值。",
    "quant.saved_notice_BASIS_MISMATCH": "记录的评估基础不同。页面保留并排数值，差值不可用；请在“比较基础检查”中查看具体字段。",
    "quant.saved_notice_TEST_DESCRIPTIVE_ONLY": "此次比较包含 TEST，仅展示描述性并排指标，全部数值差值不可用。",
    "comparison.BASIS_MISMATCH": "基础不同", "comparison.TEST_DESCRIPTIVE_ONLY": "TEST：仅描述",
    "comparison.LEFT_UNAVAILABLE": "A 不可用", "comparison.RIGHT_UNAVAILABLE": "B 不可用",
    "comparison.BOTH_UNAVAILABLE": "A、B 均不可用", "comparison.NOT_APPLICABLE": "不适用",
    "comparison.UNAVAILABLE_STATISTIC": "统计量不可用", "comparison.ZERO_VOLATILITY": "零波动",
    "comparison.INSUFFICIENT_DAILY_RETURNS": "日收益样本不足", "comparison.NO_COMPLETE_TARGETS": "无完整目标值",
    "comparison.UNSUPPORTED_EXECUTION_OR_COST_VERSION": "不支持的执行或成本版本",
    "comparison.RECORDED_CASH_RECONCILIATION_FAILED": "记录的现金无法核对一致",
    "comparison.RECORDED": "已保存记录", "comparison.RECORDED_LEDGER_DERIVATION": "账本归因",
    "comparison.RECORDED_DIFFERENCE": "已保存数值之差", "comparison.PERCENTAGE_POINTS": "百分点",
    "comparison.MATCH": "一致", "comparison.DIFFERENT": "不同", "comparison.MISSING": "未包含",
    "comparison.unnamed": "未命名", "comparison.candidate": "策略", "comparison.benchmark": "基准",
    "comparison.INTRADAY_COMPARISON": "开发期比较", "comparison.INTRADAY_DIAGNOSTICS": "开发期诊断",
    "comparison.INTRADAY_TEST": "冻结 TEST", "comparison.initial_cash": "初始资金", "comparison.final_cash": "最终资金",
    "comparison.mean_daily_return": "平均日收益", "comparison.return_count": "日收益样本数",
    "comparison.prediction_count": "预测数量", "comparison.complete_target_count": "完整目标数量",
    "comparison.evaluation_scope": "评估范围", "comparison.data_id": "数据 ID", "comparison.symbol": "标的",
    "comparison.interval": "间隔", "comparison.target_horizon_bars": "目标跨度（bar）", "comparison.split": "交易日切分",
    "comparison.session_clocks": "交易时段时钟", "comparison.price_evidence_id": "价格证据 ID",
    "comparison.raw_prices": "原始价格序列", "comparison.decision_identity": "决策身份键",
    "comparison.development_folds": "开发期折叠窗口", "comparison.event_order": "事件顺序",
    "comparison.strategy_risk": "策略风险定义", "comparison.benchmark_risk": "基准风险定义",
    "comparison.benchmark_definition": "基准定义", "comparison.performance_derivation": "归因定义",
    "comparison.feature_fields": "特征及顺序", "comparison.strategy.name": "策略名称",
    "comparison.strategy.kind": "策略类型", "comparison.strategy.alpha": "Ridge alpha",
    "comparison.strategy.threshold": "策略阈值", "comparison.strategy.signal_field": "规则特征",
    "comparison.strategy.comparator": "规则比较符", "comparison.strategy.conditions": "规则条件",
    "comparison.strategy.match": "规则组合方式", "comparison.execution_policy.entry_delay_minutes": "开盘后禁入（分钟）",
    "comparison.execution_policy.stop_new_minutes": "收盘前停止入场（分钟）",
    "comparison.execution_policy.flatten_minutes": "收盘前清仓（分钟）",
    "comparison.execution_policy.max_hold_bars": "最长持有（bar）",
    "comparison.execution_policy.commission_bps": "单边佣金（bps）",
    "comparison.execution_policy.slippage_bps": "单边滑点（bps）",
    "comparison.walk_forward": "滚动评估计划", "comparison.walk_forward.minimum_train_days": "最少训练日数",
    "comparison.walk_forward.validation_days": "验证日数", "comparison.walk_forward.step_days": "步进日数",
    "operation.intraday_compare_open_left": "打开日内已存实验 A", "operation.intraday_compare_open_right": "打开日内已存实验 B",
    "operation.intraday_compare_saved": "比较已保存日内实验",
})
for key, english, chinese in (
    ("data", "Data", "数据"), ("research", "Research", "研究"), ("walk_forward", "Walk-forward", "滚动评估"),
    ("execution", "Execution", "执行"), ("cost", "Cost", "成本"), ("daily_risk", "Daily risk", "日风险"),
    ("benchmark", "Benchmark", "基准"), ("selection", "Selection", "冻结选择"), ("final_test", "Final TEST", "最终 TEST"),
    ("final_context", "Final context", "最终上下文"), ("ridge", "Ridge", "Ridge"), ("composite", "Composite rule", "复合规则"),
):
    EN["comparison.algorithm_versions." + key] = english + " version"
    ZH_CN["comparison.algorithm_versions." + key] = chinese + "版本"
for key, english, chinese in (
    ("training_boundary", "Training boundary", "训练边界"), ("training_keys", "Training keys", "训练键"),
    ("purged_keys", "Purged keys", "剔除键"), ("test_keys", "TEST keys", "TEST 键"),
):
    EN["comparison.test_context." + key] = "TEST: " + english
    ZH_CN["comparison.test_context." + key] = "TEST：" + chinese

TRANSLATIONS: Final[dict[str, dict[str, str]]] = {
    "en": EN,
    "zh-CN": ZH_CN,
}


def translation_keys_match() -> bool:
    return set(EN) == set(ZH_CN)


class I18nBridge(QObject):
    """Expose live translations without importing the legacy Console package."""

    languageChanged = Signal()

    def __init__(
        self,
        *,
        preference_store: DesktopPreferenceStore | None = None,
        parent: QObject | None = None,
    ) -> None:
        super().__init__(parent)
        self._preference_store = preference_store or DesktopPreferenceStore()
        self._language = self._preference_store.load_language()

    @Property(str, notify=languageChanged)
    def language(self) -> str:
        return self._language

    @Property("QVariantMap", notify=languageChanged)
    def catalog(self) -> dict[str, str]:
        return dict(TRANSLATIONS[self._language])

    @Property("QVariantList", constant=True)
    def availableLanguages(self) -> list[dict[str, str]]:  # noqa: N802
        return [
            {"code": "zh-CN", "label": "中文"},
            {"code": "en", "label": "English"},
        ]

    @Slot(str, result=bool)
    def setLanguage(self, locale: str) -> bool:  # noqa: N802
        if locale not in SUPPORTED_LANGUAGES:
            return False
        if locale == self._language:
            return True
        if not self._preference_store.save_language(locale):
            return False
        self._language = locale
        self.languageChanged.emit()
        return True

    @Slot(str, result=str)
    def translate(self, key: str) -> str:
        return TRANSLATIONS[self._language].get(key, EN.get(key, key))

    @Slot(str, result=str)
    def columnLabel(self, raw_key: str) -> str:  # noqa: N802
        key = f"columns.{raw_key}"
        return self.translate(key) if key in EN else raw_key

    @Slot(str, result=str)
    def statusLabel(self, raw_status: str) -> str:  # noqa: N802
        key = f"status.{str(raw_status).strip().lower()}"
        return self.translate(key) if key in EN else str(raw_status)

    @Slot(str, result=str)
    def operationLabel(self, operation_id: str) -> str:  # noqa: N802
        key = f"operation.{str(operation_id).strip()}"
        return self.translate(key) if key in EN else str(operation_id)
