"""Fixed L4 known answers over the unchanged Dataset identity encoding."""

import inspect

import pytest

from market_vault.dataset.encoding import encode_identity
from market_vault.schedule_artifact import _identity as identity_module
from market_vault.schedule_artifact._canonical import _canonical_json
from market_vault.schedule_artifact._identity import _DOMAINS, _identity, _sha256


PAYLOAD = {"z": [None, True, 1, {"\u00e9": "value"}], "a": "US"}
CANONICAL = b'{"a":"US","z":[null,true,1,{"\\u00e9":"value"}]}\n'
PAYLOAD_SHA = "06a2511fee39342bf20ba3ad7b39e7ecbfb7908479bde0efb48ee9543b755846"
# Generated once with existing encode_identity, independently checked against
# its documented v1 tagged-scalar SHA256 preimage; never generated by this helper.
ANSWERS = {
    "l4-trading-day-source-record-v1":
        "47f3539bba0f1e2d8fb486376d36bd3391f52d81c3a05ae6328d62e0c95bd837",
    "l4-trading-day-source-snapshot-v1":
        "36be77ab6dacd62e75ccda33d6dc0d8ab81d677133358164616b3b7951ab0a74",
    "l4-trading-day-coverage-completion-v1":
        "9d43e3e85a51fabe6f8a0764788bf44ab4658886a3189bfd7d887af3439043a4",
    "l4-trading-day-schedule-artifact-v1":
        "6a0ce285dd3395141d492bbe2cc49bbfcf798342b7eca641e8038ae913cecd6e",
}


def test_canonical_payload_sha256_known_answer():
    assert _canonical_json(PAYLOAD) == CANONICAL
    assert _sha256(CANONICAL) == PAYLOAD_SHA
    assert _sha256(b"") == (
        "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
    )


@pytest.mark.parametrize("domain,expected", ANSWERS.items())
def test_identity_known_answer_and_insertion_order(domain, expected):
    assert _identity(domain, PAYLOAD) == expected
    assert _identity(domain, dict(reversed(list(PAYLOAD.items())))) == expected
    assert _identity(domain, {**PAYLOAD, "a": "CA"}) != expected


def test_exact_four_domain_separation():
    assert _DOMAINS == frozenset(ANSWERS)
    assert len({_identity(domain, PAYLOAD) for domain in ANSWERS}) == 4


@pytest.mark.parametrize("domain", [
    "", "l4-trading-day-source-record-v2", "l4-trading-day-anything-v1",
    "multi-source-cross-day-dataset-id-v1",
    "l4-trading-day-source-record-v1 ", "L4-trading-day-source-record-v1",
])
def test_unknown_domain_fails_closed(domain):
    with pytest.raises(ValueError, match="unrecognized"):
        _identity(domain, PAYLOAD)


@pytest.mark.parametrize("domain", [None, b"l4-trading-day-source-record-v1", [],
                                      type("StrSubclass", (str,), {})(
                                          "l4-trading-day-source-record-v1")])
def test_domain_requires_exact_string(domain):
    with pytest.raises(TypeError):
        _identity(domain, PAYLOAD)


@pytest.mark.parametrize("data", ["bytes", bytearray(b"bytes"), memoryview(b"bytes"),
                                   type("BytesSubclass", (bytes,), {})(b"bytes")])
def test_sha256_requires_exact_bytes(data):
    with pytest.raises(TypeError):
        _sha256(data)


def test_identity_uses_existing_encoder_and_has_no_physical_inputs(monkeypatch):
    assert identity_module.encode_identity is encode_identity
    assert tuple(inspect.signature(_identity).parameters) == ("domain", "payload")
    assert tuple(inspect.signature(_sha256).parameters) == ("data",)
    calls = []

    def record(domain, fields):
        calls.append((domain, fields))
        return encode_identity(domain, fields)

    monkeypatch.setattr(identity_module, "encode_identity", record)
    domain = "l4-trading-day-source-record-v1"
    assert _identity(domain, PAYLOAD) == ANSWERS[domain]
    assert calls == [(domain, {"canonical_payload_sha256": PAYLOAD_SHA})]


def test_identity_rejects_noncanonical_payload():
    with pytest.raises(TypeError):
        _identity("l4-trading-day-source-record-v1", {"value": 0.0})
    with pytest.raises(ValueError):
        _identity("l4-trading-day-source-record-v1", {"value": "e\u0301"})
